### ISSUE TITLE
Is it supported?

### ISSUE THREAD

**Issue by likern** [tranhl/find-then-jump#15]
Hello! Thank you for your plugin, it looks awesome, even though a lot of features still are desired.

What is a status of this plugin? Is it still supported? Bug fixes only, or maybe new features are implemented?

I've found several plugins, and of the most interesting is, unfortunately only available for Emacs ;(
https://github.com/abo-abo/avy

**Comment by tranhl** [comment]
Heyo! Yes it's still supported, I use this extension everyday in my day-to-day workflow :). If you have feature suggestions, feel free to create a new issue and request them, or make a PR and contribute to the extension.

**Comment by tranhl** [comment]
Locking due to lack of response.
