### ISSUE TITLE
Long startup activation time

### ISSUE THREAD

**Issue by aNickzz** [tranhl/find-then-jump#16]
The startup time is consistently around 350 - 400ms, which seems to be far too long for what this extension does.

(from `Developer: Show running extensions`): 
![image](https://user-images.githubusercontent.com/15243523/71796126-383ef100-3099-11ea-826d-4e2ecf629583.png)

Is anyone else experiencing this or is it potentially something wrong with my setup?

Most other extensions start up within 50ms

**Comment by tranhl** [comment]
Looks like it isn't just you, I'll do some looking around to see what could be the issue, 400ms is crazy long for what this extension does at the moment.
