### ISSUE TITLE
The original code overlaps the jump tags

### ISSUE THREAD

**Issue by shugo256** [tranhl/find-then-jump#24]
Sometimes my code overlaps the tag letter and it's hard to distinguish them.
This might be caused by the intelisence because this doesn't happen when I disable it.

Is it possible to put the tags in front of everything in the canvas?

I don't know anything about VSCode APIs, but specifying the `DecorationOptions` parameter of [`setDecorations`](https://code.visualstudio.com/api/references/vscode-api#setDecorations) API might be the solution.

<img width="267" alt="スクリーンショット 2020-04-20 0 06 48" src="https://user-images.githubusercontent.com/35961216/79691539-2f1a0e80-829b-11ea-8b21-472783814ed6.png">

**Comment by tranhl** [comment]
Unfortunately it isn’t possible to force a single text decoration to display over decorated text. Text decorations are not intended to replace the content of the text that they decorate. I work around this by creating two decorations, one that masks the text by setting the decoration foreground colour to transparent, and the background to the intended background colour. The other decoration holds the text in a `:after` pseudo element.

It appears that the transparent colour rule isn’t being properly applied in your editor setup. Could you explain what you mean by disabling intellisense? I’ll be able to quickly fix the bug if I can reproduce it consistently.

**Comment by shugo256** [comment]
Thanks for the quick reply.

The overlap occurs when I enable the official C++ extention (`ms-vscode.cpptools`) which includes intellisence. It doesn't occur if I disable it, or use other languages that I don't use intellisence with such as Python, Rust, Ruby,  and JS. Plus, it doesn't happen while the intelisence is scanning and has not taken effect even if I'm using the C++ extention.
That's why I initially thought the cause might be the intelisence.

The color theme I'm using is Monokai(`monokai.theme-monokai-pro-vscode
`) but the same bug shows up with Dark+(default dark theme) and Light+(default light theme).

**Comment by tranhl** [comment]
I've published a fix via #26. If the problem persists I'll re-open this issue. Thanks!

**Comment by shugo256** [comment]
It works perfectly 🎉 
Thank you so much!!
