### ISSUE TITLE
Find then jump disappears when autosave is enabled

### ISSUE THREAD

**Issue by gabrielecirulli** [tranhl/find-then-jump#27]
While editing TypeScript files, I have VSCode set to auto save on focus lost, and apply formatting automatically on save. Pressing the keyboard shortcut that enables Find Then Jump causes the editor to lose focus and to save. This causes Find Then Jump to close automatically right after it opens. When the file is saved before I trigger the keyboard shortcut, the extension works correctly. 

Other dialogs such as the file switcher don't seem to disappear automatically when the focus is lost.

To reproduce:
 - Set the `Files: Auto Save` setting to `onFocusChange`
 - Enable `Editor: Format On Save`
 - Enable `JavaScript > Format: Enable`
 - Create and save an empty JavaScript file
 - Enter a bit of code, then before saving or clicking away from the editor, trigger the extension via a keyboard shortcut

Actual result:
The extensions appears for a split second and then disappears

Expected result:
The extension appears and stays in place

**Comment by tranhl** [comment]
Thanks for the detailed bug report! Thanks to that I've managed to reproduce the bug locally. I'll work to get a bugfix in ASAP.

**Comment by tranhl** [comment]
Fixed via #28. If the bug persists comment here and I'll reopen the issue.

**Comment by gabrielecirulli** [comment]
That’s a very quick turnaround! Thanks for the great extension. 😄

**Comment by gabrielecirulli** [comment]
I believe this might've caused a new issue: now when I enter the letter corresponding to the token I want to select, that letter just gets typed into the field instead of moving the cursor to the correpsonding token.

**Comment by tranhl** [comment]
Yep I can reproduce that as well. The strange thing is that if format on save is disabled, the extension functions as expected. Will have to do some looking into it.

**Comment by tranhl** [comment]
Fixed via #29.
