### ISSUE TITLE
Miss jump point

### ISSUE THREAD

**Issue by rajinder-yadav** [tranhl/find-then-jump#37]
Place cursor at N (line 2), then try to jump to the last "Navbar" at the bottom. This is not getting selected as jump point when I type "n", see image.

__Sample  HTML__

```html
<template>
  <Navbar />
</template>

<script lang="ts">
import { defineComponent } from "vue";
import Navbar from "@/components/Navbar.vue"; // @ is an alias to /src

export default defineComponent({
  name: "Home",
  components: {
    Navbar
  }
});
</script>
```

![snap-32](https://user-images.githubusercontent.com/439226/110229155-5f7b9300-7ed5-11eb-9b60-5ae2f00ffa49.png)

**Comment by tranhl** [comment]
This isn't a bug. This is due to the extension running out of valid single-character jump points (Note how the last jump point is capital `Z`). If you type `na`, you'll be able to narrow down the jump points such that you can jump to `Navbar`.
